version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend/scenario-tool-suite
      dockerfile: Dockerfile
    container_name: openscenario-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - openscenario-network
    environment:
      - VITE_API_URL=/api
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: ./app/backend/openscenario-api-service/Dockerfile
    container_name: openscenario-backend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - VALIDATOR_PATH=/app/OpenSCENARIOValidator
      - LD_LIBRARY_PATH=/usr/local/lib
      - PORT=8080
      - LOG_LEVEL=INFO
      - MAX_UPLOAD_SIZE=10485760  # 10MB
    command: >-
      /bin/sh -c '
        echo "Current directory: " &&
        pwd &&
        echo "Files in /app:" &&
        ls -la /app &&
        echo "Python path:" &&
        python -c "import sys; print(sys.path)" &&
        python -m uvicorn main:app --host 0.0.0.0 --port 8080 --workers 1
      '
    networks:
      - openscenario-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  openscenario-network:
    driver: bridge

volumes:
  validator-data:
