global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # OpenSCENARIO Backend Service
  - job_name: 'openscenario-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics (if needed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker containers monitoring (disabled - not available)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['docker-exporter:9323']
  #   scrape_interval: 15s

  # Frontend service (disabled due to CORS issues)
  # - job_name: 'openscenario-frontend'
  #   static_configs:
  #     - targets: ['frontend:3000']
  #   metrics_path: '/health'
  #   scrape_interval: 30s
  #   scrape_timeout: 10s

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Loki monitoring
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'
    scrape_interval: 30s