---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9096
    
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_binary:
              endpoint: 0.0.0.0:6832
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_http:
              endpoint: 0.0.0.0:14268
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        opencensus:
          endpoint: 0.0.0.0:55678
    
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      trace_idle_period: 10s
      max_block_bytes: 1048576
      max_block_duration: 5m
    
    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 1h
        compacted_block_retention: 10m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
    
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: openscenario-cluster
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
            send_exemplars: true
    
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
        pool:
          max_workers: 100
          queue_depth: 10000
    
    querier:
      frontend_worker:
        frontend_address: tempo-query-frontend:9095
    
    query_frontend:
      search:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
      trace_by_id:
        duration_slo: 5s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.2.0
        args:
          - -config.file=/etc/tempo/tempo.yml
          - -mem-ballast-size-mbs=1024
        ports:
        - containerPort: 3200
          name: http
        - containerPort: 9096
          name: grpc
        - containerPort: 6831
          name: jaeger-thrift-c
          protocol: UDP
        - containerPort: 6832
          name: jaeger-thrift-b
          protocol: UDP
        - containerPort: 14250
          name: jaeger-grpc
        - containerPort: 14268
          name: jaeger-http
        - containerPort: 9411
          name: zipkin
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 55678
          name: opencensus
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /etc/tempo
        - name: storage
          mountPath: /tmp/tempo
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
      volumes:
      - name: config
        configMap:
          name: tempo-config
      - name: storage
        persistentVolumeClaim:
          claimName: tempo-storage

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app: tempo
spec:
  ports:
  - port: 3200
    targetPort: 3200
    name: http
  - port: 9096
    targetPort: 9096
    name: grpc
  - port: 6831
    targetPort: 6831
    name: jaeger-thrift-c
    protocol: UDP
  - port: 6832
    targetPort: 6832
    name: jaeger-thrift-b
    protocol: UDP
  - port: 14250
    targetPort: 14250
    name: jaeger-grpc
  - port: 14268
    targetPort: 14268
    name: jaeger-http
  - port: 9411
    targetPort: 9411
    name: zipkin
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    name: otlp-http
  - port: 55678
    targetPort: 55678
    name: opencensus
  selector:
    app: tempo

---
# Tempo Query Frontend for better query performance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-query-frontend
  namespace: monitoring
  labels:
    app: tempo-query-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo-query-frontend
  template:
    metadata:
      labels:
        app: tempo-query-frontend
    spec:
      containers:
      - name: tempo-query-frontend
        image: grafana/tempo:2.2.0
        args:
          - -target=query-frontend
          - -config.file=/etc/tempo/tempo.yml
        ports:
        - containerPort: 3200
          name: http
        - containerPort: 9095
          name: grpc
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /etc/tempo
      volumes:
      - name: config
        configMap:
          name: tempo-config

---
apiVersion: v1
kind: Service
metadata:
  name: tempo-query-frontend
  namespace: monitoring
  labels:
    app: tempo-query-frontend
spec:
  ports:
  - port: 3200
    targetPort: 3200
    name: http
  - port: 9095
    targetPort: 9095
    name: grpc
  selector:
    app: tempo-query-frontend