all:
  children:
    frontend:
      hosts:
        frontend-1:
          ansible_host: "{{ lookup('aws_ec2', 'tag:Environment=prod tag:Name=frontend-1') }}"
          ansible_user: ubuntu
        frontend-2:
          ansible_host: "{{ lookup('aws_ec2', 'tag:Environment=prod tag:Name=frontend-2') }}"
          ansible_user: ubuntu
      vars:
        environment: prod
        app_type: frontend

    backend:
      hosts:
        backend-1:
          ansible_host: "{{ lookup('aws_ec2', 'tag:Environment=prod tag:Name=backend-1') }}"
          ansible_user: ubuntu
        backend-2:
          ansible_host: "{{ lookup('aws_ec2', 'tag:Environment=prod tag:Name=backend-2') }}"
          ansible_user: ubuntu
      vars:
        environment: prod
        app_type: backend

  vars:
    ansible_python_interpreter: /usr/bin/python3
    environment: prod 